-- =====================================================================
--  FOOD DELIVERY APP (Swiggy-style) : DATABASE SCHEMA
--  PostgreSQL 14+
--
--  Run order:
--     01_schema.sql            <- this file (all tables)
--     02_payment_security.sql  <- CVV / card-data protection rules
--     03_seed.sql              <- sample data
--     04_flow_walkthrough.sql  <- one full order, step by step (optional)
--
--  Groups (same colours as the mind map):
--     A. Shared identity      : users, roles, user_roles, otp_requests
--     B. Customer app         : addresses, carts, cart_items, coupons, ratings
--     C. Restaurant app       : restaurants, restaurant_staff, restaurant_timings,
--                               menu_categories, menu_items, item_addons, restaurant_payouts
--     D. Delivery partner app : delivery_partners, partner_documents, partner_locations,
--                               delivery_assignments, partner_earnings
--     E. Order core           : orders, order_items, order_status_history
--     F. Payment gateway      : payment_gateways, saved_payment_methods, payments,
--                               payment_transactions, refunds, payment_webhook_events
--
--  !!! CARD DATA RULE !!!
--  There is NO column anywhere in this database for CVV/CVC or the full
--  card number. The app never receives them: the payment gateway's SDK
--  collects them and gives us a TOKEN. See 02_payment_security.sql.
-- =====================================================================

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
SET search_path = public;

-- Helper: keeps updated_at current on every UPDATE
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$ LANGUAGE plpgsql;

-- =====================================================================
-- A. SHARED IDENTITY
-- =====================================================================
CREATE TABLE users (
  user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone        VARCHAR(15)  NOT NULL UNIQUE,              -- login is by OTP to this phone
  name         VARCHAR(100),
  email        VARCHAR(150) UNIQUE,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT chk_users_phone CHECK (phone ~ '^\+?[0-9]{10,14}$')
);

CREATE TABLE roles (
  role_id    SMALLINT    PRIMARY KEY,
  role_name  VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
  user_id     BIGINT   NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  role_id     SMALLINT NOT NULL REFERENCES roles(role_id),
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role_id)
);

-- OTP login. We store only a HASH of the OTP, never the OTP itself.
CREATE TABLE otp_requests (
  otp_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone       VARCHAR(15)  NOT NULL,
  otp_hash    VARCHAR(128) NOT NULL,
  expires_at  TIMESTAMPTZ  NOT NULL,
  attempts    SMALLINT     NOT NULL DEFAULT 0,
  verified    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_otp_phone ON otp_requests(phone, created_at DESC);

-- =====================================================================
-- C. RESTAURANT APP  (created before customer tables because carts point to it)
-- =====================================================================
CREATE TABLE restaurants (
  restaurant_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(150) NOT NULL,
  address_line   TEXT         NOT NULL,
  city           VARCHAR(60)  NOT NULL,
  latitude       DECIMAL(9,6) NOT NULL,
  longitude      DECIMAL(9,6) NOT NULL,
  cuisines       VARCHAR(200),
  fssai_no       VARCHAR(20)  UNIQUE,
  gst_no         VARCHAR(20),
  status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                 CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','CLOSED')),
  is_open        BOOLEAN      NOT NULL DEFAULT FALSE,
  avg_rating     DECIMAL(2,1) NOT NULL DEFAULT 0,
  rating_count   INT          NOT NULL DEFAULT 0,
  avg_prep_mins  INT          NOT NULL DEFAULT 20,
  commission_pct DECIMAL(4,2) NOT NULL DEFAULT 18.00,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_restaurants_city_status ON restaurants(city, status, is_open);

CREATE TABLE restaurant_staff (
  restaurant_id BIGINT NOT NULL REFERENCES restaurants(restaurant_id) ON DELETE CASCADE,
  user_id       BIGINT NOT NULL REFERENCES users(user_id),
  staff_role    VARCHAR(20) NOT NULL CHECK (staff_role IN ('OWNER','MANAGER','KITCHEN')),
  PRIMARY KEY (restaurant_id, user_id)
);

CREATE TABLE restaurant_timings (
  timing_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT   NOT NULL REFERENCES restaurants(restaurant_id) ON DELETE CASCADE,
  day_of_week   SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),   -- 1 = Monday
  open_time     TIME     NOT NULL,
  close_time    TIME     NOT NULL,
  UNIQUE (restaurant_id, day_of_week, open_time)
);

CREATE TABLE menu_categories (
  category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT      NOT NULL REFERENCES restaurants(restaurant_id) ON DELETE CASCADE,
  name          VARCHAR(50) NOT NULL,
  sort_order    INT         NOT NULL DEFAULT 0
);

CREATE TABLE menu_items (
  item_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT       NOT NULL REFERENCES restaurants(restaurant_id) ON DELETE CASCADE,
  category_id   BIGINT       NOT NULL REFERENCES menu_categories(category_id),
  name          VARCHAR(150) NOT NULL,
  description   TEXT,
  price         DECIMAL(8,2) NOT NULL CHECK (price > 0),
  is_veg        BOOLEAN      NOT NULL,
  in_stock      BOOLEAN      NOT NULL DEFAULT TRUE,
  image_url     TEXT,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_menu_items_restaurant ON menu_items(restaurant_id, in_stock);

CREATE TABLE item_addons (
  addon_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id   BIGINT       NOT NULL REFERENCES menu_items(item_id) ON DELETE CASCADE,
  name      VARCHAR(80)  NOT NULL,
  price     DECIMAL(8,2) NOT NULL CHECK (price >= 0),
  in_stock  BOOLEAN      NOT NULL DEFAULT TRUE
);

-- =====================================================================
-- B. CUSTOMER APP
-- =====================================================================
CREATE TABLE addresses (
  address_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT       NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  label         VARCHAR(20)  NOT NULL DEFAULT 'Home',
  address_line  TEXT         NOT NULL,
  landmark      VARCHAR(100),
  city          VARCHAR(60)  NOT NULL,
  latitude      DECIMAL(9,6) NOT NULL,
  longitude     DECIMAL(9,6) NOT NULL,
  is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_addresses_user ON addresses(user_id);

CREATE TABLE carts (
  cart_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,  -- one active cart per user
  restaurant_id BIGINT REFERENCES restaurants(restaurant_id),                         -- one restaurant per cart
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cart_items (
  cart_item_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id         BIGINT NOT NULL REFERENCES carts(cart_id) ON DELETE CASCADE,
  item_id         BIGINT NOT NULL REFERENCES menu_items(item_id),
  quantity        INT    NOT NULL CHECK (quantity BETWEEN 1 AND 50),
  selected_addons JSONB  NOT NULL DEFAULT '[]'::jsonb,       -- e.g. [301, 302] (addon_ids)
  UNIQUE (cart_id, item_id, selected_addons)
);

CREATE TABLE coupons (
  coupon_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code             VARCHAR(20)  NOT NULL UNIQUE,
  description      VARCHAR(200),
  discount_type    VARCHAR(10)  NOT NULL CHECK (discount_type IN ('FLAT','PERCENT')),
  discount_value   DECIMAL(8,2) NOT NULL CHECK (discount_value > 0),
  min_order_value  DECIMAL(8,2) NOT NULL DEFAULT 0,
  max_discount     DECIMAL(8,2),
  valid_from       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_till       TIMESTAMPTZ  NOT NULL,
  is_active        BOOLEAN      NOT NULL DEFAULT TRUE
);

-- =====================================================================
-- D. DELIVERY PARTNER APP (profile first; orders reference it)
-- =====================================================================
CREATE TABLE delivery_partners (
  partner_id    BIGINT PRIMARY KEY REFERENCES users(user_id),   -- same ID as the user (1-to-1)
  vehicle_type  VARCHAR(20) NOT NULL CHECK (vehicle_type IN ('BIKE','SCOOTER','CYCLE','EV')),
  vehicle_no    VARCHAR(15),
  licence_no    VARCHAR(30) UNIQUE,
  city          VARCHAR(60) NOT NULL,
  kyc_status    VARCHAR(20) NOT NULL DEFAULT 'PENDING_KYC'
                CHECK (kyc_status IN ('PENDING_KYC','VERIFIED','REJECTED')),
  is_online     BOOLEAN     NOT NULL DEFAULT FALSE,
  current_order_id BIGINT,                                      -- FK added after orders table
  rating        DECIMAL(2,1) NOT NULL DEFAULT 0,
  joined_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE partner_documents (
  doc_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id   BIGINT      NOT NULL REFERENCES delivery_partners(partner_id) ON DELETE CASCADE,
  doc_type     VARCHAR(20) NOT NULL CHECK (doc_type IN ('LICENCE','RC','ID_PROOF','PHOTO')),
  file_url     TEXT        NOT NULL,       -- file lives in object storage (S3 etc.), not in the DB
  verified     BOOLEAN     NOT NULL DEFAULT FALSE,
  verified_at  TIMESTAMPTZ,
  uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Latest GPS point only. In production this lives in Redis; here it is a small table.
CREATE TABLE partner_locations (
  partner_id  BIGINT PRIMARY KEY REFERENCES delivery_partners(partner_id) ON DELETE CASCADE,
  latitude    DECIMAL(9,6) NOT NULL,
  longitude   DECIMAL(9,6) NOT NULL,
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- =====================================================================
-- E. ORDER CORE
-- =====================================================================
CREATE TABLE orders (
  order_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     BIGINT        NOT NULL REFERENCES users(user_id),
  restaurant_id   BIGINT        NOT NULL REFERENCES restaurants(restaurant_id),
  partner_id      BIGINT        REFERENCES delivery_partners(partner_id),   -- NULL until assigned
  address_id      BIGINT        NOT NULL REFERENCES addresses(address_id),
  coupon_id       BIGINT        REFERENCES coupons(coupon_id),
  item_total      DECIMAL(10,2) NOT NULL,
  delivery_fee    DECIMAL(8,2)  NOT NULL DEFAULT 0,
  platform_fee    DECIMAL(8,2)  NOT NULL DEFAULT 0,
  taxes           DECIMAL(8,2)  NOT NULL DEFAULT 0,
  discount        DECIMAL(8,2)  NOT NULL DEFAULT 0,
  total_amount    DECIMAL(10,2) NOT NULL CHECK (total_amount >= 0),
  payment_mode    VARCHAR(10)   NOT NULL CHECK (payment_mode IN ('CARD','UPI','COD','WALLET')),
  status          VARCHAR(20)   NOT NULL DEFAULT 'PAYMENT_PENDING'
                  CHECK (status IN ('PAYMENT_PENDING','PLACED','ACCEPTED','PREPARING','READY',
                                    'PICKED_UP','DELIVERED','CANCELLED','PAYMENT_FAILED')),
  special_instructions VARCHAR(300),
  placed_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
  delivered_at    TIMESTAMPTZ,
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_orders_customer   ON orders(customer_id, placed_at DESC);
CREATE INDEX idx_orders_restaurant ON orders(restaurant_id, status);
CREATE INDEX idx_orders_partner    ON orders(partner_id, status);

ALTER TABLE delivery_partners
  ADD CONSTRAINT fk_partner_current_order FOREIGN KEY (current_order_id) REFERENCES orders(order_id);

CREATE TABLE order_items (
  order_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       BIGINT       NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  item_id        BIGINT       NOT NULL REFERENCES menu_items(item_id),
  item_name      VARCHAR(150) NOT NULL,          -- copied: menu may change later
  quantity       INT          NOT NULL CHECK (quantity > 0),
  price_at_order DECIMAL(8,2) NOT NULL,          -- copied: price may change later
  addons         JSONB        NOT NULL DEFAULT '[]'::jsonb,   -- [{"addon_id":301,"name":"Raita","price":30}]
  line_total     DECIMAL(10,2) NOT NULL
);
CREATE INDEX idx_order_items_order ON order_items(order_id);

CREATE TABLE order_status_history (
  history_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT      NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  status      VARCHAR(20) NOT NULL,
  changed_by  BIGINT      REFERENCES users(user_id),     -- NULL = system
  note        VARCHAR(200),
  changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_osh_order ON order_status_history(order_id, changed_at);

CREATE TABLE ratings (
  rating_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         BIGINT   NOT NULL UNIQUE REFERENCES orders(order_id),
  user_id          BIGINT   NOT NULL REFERENCES users(user_id),
  food_rating      SMALLINT NOT NULL CHECK (food_rating BETWEEN 1 AND 5),
  delivery_rating  SMALLINT CHECK (delivery_rating BETWEEN 1 AND 5),
  comment          TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- D (continued). DELIVERY TABLES THAT NEED ORDERS
-- =====================================================================
CREATE TABLE delivery_assignments (
  assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      BIGINT      NOT NULL REFERENCES orders(order_id),
  partner_id    BIGINT      NOT NULL REFERENCES delivery_partners(partner_id),
  status        VARCHAR(20) NOT NULL DEFAULT 'OFFERED'
                CHECK (status IN ('OFFERED','ACCEPTED','REJECTED','EXPIRED','CANCELLED')),
  offered_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  responded_at  TIMESTAMPTZ
);
-- only ONE accepted assignment per order
CREATE UNIQUE INDEX uq_one_accepted_assignment ON delivery_assignments(order_id) WHERE status = 'ACCEPTED';

CREATE TABLE partner_earnings (
  earning_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id     BIGINT       NOT NULL REFERENCES delivery_partners(partner_id),
  order_id       BIGINT       NOT NULL UNIQUE REFERENCES orders(order_id),
  base_pay       DECIMAL(8,2) NOT NULL,
  distance_pay   DECIMAL(8,2) NOT NULL DEFAULT 0,
  tip            DECIMAL(8,2) NOT NULL DEFAULT 0,
  payout_status  VARCHAR(20)  NOT NULL DEFAULT 'PENDING' CHECK (payout_status IN ('PENDING','PAID')),
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE restaurant_payouts (
  payout_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id  BIGINT        NOT NULL REFERENCES restaurants(restaurant_id),
  order_id       BIGINT        NOT NULL UNIQUE REFERENCES orders(order_id),
  order_amount   DECIMAL(10,2) NOT NULL,
  commission     DECIMAL(10,2) NOT NULL,
  payout_amount  DECIMAL(10,2) NOT NULL,
  payout_status  VARCHAR(20)   NOT NULL DEFAULT 'PENDING' CHECK (payout_status IN ('PENDING','PAID')),
  created_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- =====================================================================
-- F. PAYMENT GATEWAY
--    The full card number and CVV NEVER reach these tables.
--    The gateway (Razorpay / Stripe / etc.) collects them in its own SDK
--    and returns a TOKEN. We store only: token, card brand, last 4 digits,
--    expiry month/year - all allowed by PCI-DSS.
-- =====================================================================
CREATE TABLE payment_gateways (
  gateway_id    SMALLINT    PRIMARY KEY,
  code          VARCHAR(20) NOT NULL UNIQUE,       -- MOCKPAY, RAZORPAY, STRIPE
  display_name  VARCHAR(50) NOT NULL,
  supports_card BOOLEAN     NOT NULL DEFAULT TRUE,
  supports_upi  BOOLEAN     NOT NULL DEFAULT TRUE,
  is_active     BOOLEAN     NOT NULL DEFAULT FALSE,
  priority      SMALLINT    NOT NULL DEFAULT 10    -- lower = tried first
  -- API keys / secrets are NOT stored here. They live in environment variables / a secrets vault.
);

-- Cards / UPI IDs the customer chose to save ("Saved cards" screen).
CREATE TABLE saved_payment_methods (
  method_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            BIGINT      NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  gateway_id         SMALLINT    NOT NULL REFERENCES payment_gateways(gateway_id),
  method_type        VARCHAR(10) NOT NULL CHECK (method_type IN ('CARD','UPI')),
  gateway_token      VARCHAR(100) NOT NULL UNIQUE,  -- token from the gateway, useless outside it
  card_network       VARCHAR(20),                    -- VISA / MASTERCARD / RUPAY / AMEX
  card_last4         CHAR(4),                        -- only the last 4 digits, for display
  card_expiry_month  SMALLINT,
  card_expiry_year   SMALLINT,
  upi_vpa_masked     VARCHAR(60),                    -- e.g. ra****@okaxis
  is_default         BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_last4      CHECK (card_last4 IS NULL OR card_last4 ~ '^[0-9]{4}$'),
  CONSTRAINT chk_exp_month  CHECK (card_expiry_month IS NULL OR card_expiry_month BETWEEN 1 AND 12),
  CONSTRAINT chk_card_cols  CHECK (method_type <> 'CARD' OR (card_last4 IS NOT NULL AND card_network IS NOT NULL))
);

CREATE TABLE payments (
  payment_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id            BIGINT        NOT NULL REFERENCES orders(order_id),
  user_id             BIGINT        NOT NULL REFERENCES users(user_id),
  gateway_id          SMALLINT      REFERENCES payment_gateways(gateway_id),   -- NULL for COD
  method_type         VARCHAR(10)   NOT NULL CHECK (method_type IN ('CARD','UPI','COD','WALLET')),
  saved_method_id     BIGINT        REFERENCES saved_payment_methods(method_id),
  card_network        VARCHAR(20),       -- copied for receipts ("VISA •••• 1111")
  card_last4          CHAR(4) CHECK (card_last4 IS NULL OR card_last4 ~ '^[0-9]{4}$'),
  amount              DECIMAL(10,2) NOT NULL CHECK (amount >= 0),
  currency            CHAR(3)       NOT NULL DEFAULT 'INR',
  status              VARCHAR(20)   NOT NULL DEFAULT 'CREATED'
                      CHECK (status IN ('CREATED','PENDING','AUTHORIZED','CAPTURED','FAILED',
                                        'REFUNDED','PARTIALLY_REFUNDED','COD_PENDING','COD_COLLECTED')),
  idempotency_key     VARCHAR(64)   NOT NULL UNIQUE,  -- stops double charging if the user taps twice
  gateway_order_ref   VARCHAR(100)  UNIQUE,           -- order id created at the gateway
  gateway_payment_ref VARCHAR(100)  UNIQUE,           -- payment id returned by the gateway
  failure_code        VARCHAR(50),
  failure_reason      VARCHAR(200),
  created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_order ON payments(order_id);

-- Every call we make to the gateway (authorize, capture, refund) = one row.
CREATE TABLE payment_transactions (
  txn_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id        BIGINT        NOT NULL REFERENCES payments(payment_id),
  txn_type          VARCHAR(20)   NOT NULL CHECK (txn_type IN ('CREATE_ORDER','AUTHORIZE','CAPTURE','REFUND','VOID')),
  amount            DECIMAL(10,2) NOT NULL,
  status            VARCHAR(20)   NOT NULL CHECK (status IN ('SUCCESS','FAILED','PENDING')),
  gateway_txn_ref   VARCHAR(100),
  gateway_response  JSONB         NOT NULL DEFAULT '{}'::jsonb,   -- SANITISED response (checked by trigger)
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_ptxn_payment ON payment_transactions(payment_id);

CREATE TABLE refunds (
  refund_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id         BIGINT        NOT NULL REFERENCES payments(payment_id),
  amount             DECIMAL(10,2) NOT NULL CHECK (amount > 0),
  reason             VARCHAR(200),
  status             VARCHAR(20)   NOT NULL DEFAULT 'INITIATED'
                     CHECK (status IN ('INITIATED','PROCESSED','FAILED')),
  gateway_refund_ref VARCHAR(100)  UNIQUE,
  initiated_by       BIGINT        REFERENCES users(user_id),
  created_at         TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Gateway calls us back (webhook) when a payment succeeds/fails.
CREATE TABLE payment_webhook_events (
  event_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gateway_id        SMALLINT     NOT NULL REFERENCES payment_gateways(gateway_id),
  gateway_event_id  VARCHAR(100) NOT NULL,          -- gateway's own event id
  event_type        VARCHAR(60)  NOT NULL,          -- payment.captured, payment.failed, refund.processed
  payment_id        BIGINT       REFERENCES payments(payment_id),
  signature_valid   BOOLEAN      NOT NULL,
  payload           JSONB        NOT NULL,          -- SANITISED payload (checked by trigger)
  received_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  processed_at      TIMESTAMPTZ,
  UNIQUE (gateway_id, gateway_event_id)             -- same webhook delivered twice = ignored
);

-- =====================================================================
-- updated_at triggers
-- =====================================================================
CREATE TRIGGER trg_users_upd       BEFORE UPDATE ON users       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_restaurants_upd BEFORE UPDATE ON restaurants FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_menu_items_upd  BEFORE UPDATE ON menu_items  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_orders_upd      BEFORE UPDATE ON orders      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_payments_upd    BEFORE UPDATE ON payments    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =====================================================================
-- Documentation stored inside the database itself
-- =====================================================================
COMMENT ON TABLE payments IS
  'One row per payment attempt. CVV/CVC and full card number are NEVER stored (PCI-DSS req. 3.3). Only gateway refs, brand and last 4 digits.';
COMMENT ON TABLE saved_payment_methods IS
  'Saved cards = gateway TOKEN + brand + last4 + expiry. No CVV, no full card number, ever.';
COMMENT ON COLUMN payment_transactions.gateway_response IS
  'Sanitised gateway response. A trigger rejects any JSON containing cvv/cvc/card_number keys or a full card number.';
COMMENT ON TABLE orders IS 'Hub table: links customer, restaurant, delivery partner, address and coupon.';
